### ISSUE TITLE
ipx.Query KeyError: 'feed'

### ISSUE THREAD

**Issue by Chrismarsh** [icesat2py/icepyx#279] opened 2022-02-18 17:43 UTC
I'm working through the notebooks in doc/source, both `IS2_data_access` and `IS2_data_access2-subsetting` but I cannot get past the first query

```
region_a = ipx.Query('ATL09',[-55, 68, -48, 71],['2019-02-22','2019-02-28'], \
                           start_time='00:00:00', end_time='23:59:59')

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/var/folders/f4/nmhnpzgx6pl0lxd79t2n48q80000gn/T/ipykernel_17325/3053781817.py in <module>
----> 1 region_a = ipx.Query('ATL08',[-55, 68, -48, 71],['2019-02-22','2019-02-28'], \
      2                            start_time='00:00:00', end_time='23:59:59')

~/.pyenv/versions/3.8.0/envs/dataspell/lib/python3.8/site-packages/icepyx/core/query.py in __init__(self, product, spatial_extent, date_range, start_time, end_time, version, cycles, tracks, files)
    152             self._start, self._end = val.temporal(date_range, start_time, end_time)
    153 
--> 154         self._version = val.prod_version(self.latest_version(), version)
    155 
    156         # build list of available CMR parameters if reducing by cycle or RGT

~/.pyenv/versions/3.8.0/envs/dataspell/lib/python3.8/site-packages/icepyx/core/query.py in latest_version(self)
    620             self._about_product = is2ref.about_product(self._prod)
    621         return max(
--> 622             [entry["version_id"] for entry in self._about_product["feed"]["entry"]]
    623         )
    624 

KeyError: 'feed'
```

I'm using the latest pip installed version.

**Comment by JessicaS11** [comment] 2022-02-25 16:40
Hello @Chrismarsh! Thanks for getting in touch. Unfortunately, I am unable to reproduce this error. I'm wondering if it could be an internet connectivity issue. Could you verify that you're still unable to run these examples, provide the output of `ipx.__version__`, and confirm which product you are trying to create your Query object for (the error message shows ATL08, but the code shows ATL09, which makes me wonder if it could also be a kernel issue). Thanks!

**Comment by JessicaS11** [comment] 2022-04-18 20:09
Hello @Chrismarsh Are you still having this issue? Otherwise I am going to close the issue. Thanks!

**Comment by Chrismarsh** [comment] 2022-04-22 22:22
Hi @JessicaS11, sorry I must have missed your first reply to this ticket!

I had to pivot away from trying the ICESAT data, but will be trying again in the next month+. If you prefer, why not close this and I can reopen it if it turns out to be more systematic?

**Closed** 2022-05-05 15:28 UTC
